apiVersion: v1
kind: Service
metadata:
  name: {{ include "renovate-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "renovate-operator.fullname" . }}
  ports:
    - protocol: TCP
      port: 8081
      name: http
      targetPort: http
