{{- if and .Values.webhook.route.enabled .Values.webhook.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "renovate-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  {{- if .Values.webhook.route.labels }}
  labels:
    {{- toYaml .Values.webhook.route.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.webhook.route.annotations }}
  annotations:
    {{- toYaml .Values.webhook.route.annotations | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- if .Values.webhook.route.parentRefs }}
    {{- toYaml .Values.webhook.route.parentRefs | nindent 4 }}
    {{- else if .Values.webhook.route.listenerset.enabled }}
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: {{ include "renovate-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      sectionName: {{ .Values.webhook.route.listenerset.listenerName }}
    {{- end }}
  {{- with .Values.webhook.route.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.webhook.route.additionalRules }}
    {{- tpl (toYaml .Values.webhook.route.additionalRules) $ | nindent 4 }}
    {{- end }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "renovate-operator.fullname" . }}
          port: {{ .Values.webhook.port }}
          group: {{ .Values.webhook.route.group | quote }}
          kind: {{ .Values.webhook.route.kind | quote }}
          weight: {{ .Values.webhook.route.weight }}
{{- end }}
