package webhook

import (
	"encoding/json"
	"io"
	"net/http"

	api "renovate-operator/api/v1alpha1"
	"renovate-operator/internal/types"
)

// Bitbucket Cloud webhook types and handler.
//
// Bitbucket dispatches by the X-Event-Key header (e.g. "pullrequest:updated").
// Renovate does not support the Dependency Dashboard on Bitbucket Cloud, so
// only pull request events are processed:
//
//   - pullrequest:updated: only if the PR is generated by Renovate and its
//     description contains a checked checkbox (e.g. the rebase checkbox)
//   - pullrequest:fulfilled / pullrequest:rejected: merge/decline of a
//     Renovate PR (the equivalent of "closed" on the other platforms)
//
// Deliveries are authenticated via the hook secret, which Bitbucket uses to
// sign the payload into the X-Hub-Signature header (sha256=<hmac>).

type BitbucketEvent struct {
	PullRequest *BitbucketPullRequest `json:"pullrequest,omitempty"`
	Repository  BitbucketRepository   `json:"repository"`
}

type BitbucketPullRequest struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type BitbucketRepository struct {
	FullName string `json:"full_name"`
}

func (s *Server) bitbucketWebhook(w http.ResponseWriter, r *http.Request) {
	event := r.Header.Get("X-Event-Key")
	if event == "" {
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "missing X-Event-Key header"})
		return
	}

	body, err := io.ReadAll(r.Body)
	if err != nil {
		s.writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to read request body"})
		return
	}

	var payload BitbucketEvent
	if err := json.Unmarshal(body, &payload); err != nil {
		s.logger.Error(err, "failed to decode Bitbucket webhook payload. Not processing.")
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "failed to decode payload"})
		return
	}

	valid, reason := isValidBitbucketEvent(event, &payload)
	if !valid {
		s.logger.Info("ignoring Bitbucket webhook event", "event", event, "repository", payload.Repository.FullName, "reason", reason)
		s.writeJSON(w, http.StatusOK, map[string]string{"message": "event ignored", "reason": reason})
		return
	}

	namespace := r.URL.Query().Get("namespace")
	jobName := r.URL.Query().Get("job")
	project := payload.Repository.FullName

	checker := buildAuthCheckerFromRequest(r, body, s.manager)
	jobId, err := FindAndAuthenticateJob(r.Context(), s.manager, namespace, jobName, project, checker)
	if err != nil {
		s.logger.Info("webhook resolve failed", "event", event, "project", project, "error", err)
		s.handleResolverError(w, err)
		return
	}

	s.logger.Info("received Bitbucket event", "event", event, "repository", project)
	err = s.manager.UpdateProjectStatus(
		r.Context(),
		project,
		jobId,
		&types.RenovateStatusUpdate{
			Status:   api.JobStatusScheduled,
			Priority: 1,
		},
	)
	if s.handleUpdateProjectStatusError(w, err, project, jobId.Name, jobId.Namespace) {
		return
	}

	s.writeJSON(w, http.StatusAccepted, map[string]string{"message": "renovate job scheduled", "repository": project})
}

func isValidBitbucketEvent(event string, payload *BitbucketEvent) (bool, string) {
	switch event {
	case "pullrequest:updated", "pullrequest:fulfilled", "pullrequest:rejected":
		if payload.PullRequest == nil {
			return false, "no pull request in payload"
		}
		if payload.PullRequest.Description == "" {
			return false, "no pull request description"
		}
		if !isRenovateContent(payload.PullRequest.Description) {
			return false, "not a Renovate pull request"
		}
		// merge/decline of a Renovate PR always triggers; description edits
		// only when a checkbox was checked
		if event == "pullrequest:updated" && !hasCheckboxBeenChecked(payload.PullRequest.Description) {
			return false, "no checked checkbox"
		}
		return true, ""

	default:
		return false, "unsupported event type: " + event
	}
}
