package webhook

import (
	"encoding/json"
	"io"
	"net/http"
)

// Bitbucket Cloud webhook types and handler.
//
// Bitbucket dispatches by the X-Event-Key header (e.g. "pullrequest:updated").
// Renovate does not support the Dependency Dashboard on Bitbucket Cloud, so
// only pull request events are processed:
//
//   - pullrequest:updated: only if the PR is generated by Renovate and its
//     description contains a checked checkbox (e.g. the rebase checkbox)
//   - pullrequest:fulfilled / pullrequest:rejected: merge/decline of a
//     Renovate PR (the equivalent of "closed" on the other platforms)
//
// Deliveries are authenticated via the hook secret, which Bitbucket uses to
// sign the payload into the X-Hub-Signature header (sha256=<hmac>).

type BitbucketEvent struct {
	PullRequest *BitbucketPullRequest `json:"pullrequest,omitempty"`
	Repository  BitbucketRepository   `json:"repository"`
}

type BitbucketPullRequest struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type BitbucketRepository struct {
	FullName string `json:"full_name"`
}

func (s *Server) bitbucketWebhook(w http.ResponseWriter, r *http.Request) {
	event := r.Header.Get("X-Event-Key")
	if event == "" {
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "missing X-Event-Key header"})
		return
	}

	body, err := io.ReadAll(r.Body)
	if err != nil {
		s.writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to read request body"})
		return
	}

	var raw BitbucketEvent
	if err := json.Unmarshal(body, &raw); err != nil {
		s.logger.Error(err, "failed to decode Bitbucket webhook payload. Not processing.")
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "failed to decode payload"})
		return
	}

	payload, valid := parseBitbucketPayload(event, &raw)
	if !valid {
		s.logger.V(5).Info("failed to parse webhook payload")
		s.writeJSON(w, http.StatusOK, map[string]string{"message": "event ignored"})
		return
	}

	s.handleWebhookTrigger(w, r, body, payload)
}

// parseBitbucketPayload normalizes a raw Bitbucket event into a WebhookPayload
// and validates it. Bitbucket's event key encodes both the object type and
// action (e.g. "pullrequest:fulfilled"), which is normalized to the standard
// action vocabulary ("edited", "closed"). Returns false when the event should
// be ignored.
func parseBitbucketPayload(event string, raw *BitbucketEvent) (WebhookPayload, bool) {
	var action string
	switch event {
	case "pullrequest:updated":
		action = "edited"
	case "pullrequest:fulfilled", "pullrequest:rejected":
		action = "closed"
	default:
		return WebhookPayload{}, false
	}

	if raw.PullRequest == nil {
		return WebhookPayload{}, false
	}

	return WebhookPayload{
		Provider:  "Bitbucket",
		Project:   raw.Repository.FullName,
		Event:     event,
		Action:    action,
		EventType: "pull_request",
		Body:      WebhookBody{Current: raw.PullRequest.Description},
	}, true
}
