package webhook

import "testing"

func TestForgejoEventValidation(t *testing.T) {
	tests := []struct {
		name    string
		event   string
		payload ForgejoEvent
		valid   bool
		reason  string
	}{
		// Issue events
		{
			name:  "issue edited with renovate checkbox checked",
			event: "issues",
			payload: ForgejoEvent{
				Action: "edited",
				Issue: &ForgejoIssue{
					Title: "Dependency Dashboard",
					Body:  "This issue lists Renovate updates and detected dependencies.\n - [x] <!-- manual job -->Check this box to trigger a request for Renovate to run again on this repository",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  true,
			reason: "",
		},
		{
			name:  "issue edited but checkbox not checked",
			event: "issues",
			payload: ForgejoEvent{
				Action: "edited",
				Issue: &ForgejoIssue{
					Title: "Dependency Dashboard",
					Body:  "This issue lists Renovate updates and detected dependencies.\n - [ ] <!-- manual job -->Check this box to trigger a request for Renovate to run again on this repository",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "not a valid renovate checkbox change",
		},
		{
			name:  "issue edited but not renovate content",
			event: "issues",
			payload: ForgejoEvent{
				Action: "edited",
				Issue: &ForgejoIssue{
					Title: "Some issue",
					Body:  "Some body with - [x] checked checkbox but not renovate",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "not a valid renovate checkbox change",
		},
		{
			name:  "issue opened is ignored",
			event: "issues",
			payload: ForgejoEvent{
				Action: "opened",
				Issue: &ForgejoIssue{
					Body: "Some body",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "issue action is not edited",
		},
		{
			name:  "issue closed is ignored",
			event: "issues",
			payload: ForgejoEvent{
				Action: "closed",
				Issue: &ForgejoIssue{
					Body: "Some body",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "issue action is not edited",
		},
		{
			name:  "issue edited with empty body",
			event: "issues",
			payload: ForgejoEvent{
				Action: "edited",
				Issue: &ForgejoIssue{
					Body: "",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "no issue body",
		},
		{
			name:  "issue edited with nil issue",
			event: "issues",
			payload: ForgejoEvent{
				Action:     "edited",
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "no issue body",
		},

		// Pull request events
		{
			name:  "renovate PR edited with checkbox checked",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "edited",
				PullRequest: &ForgejoPullRequest{
					Body: "Update dependency\n - [x] <!-- rebase-check -->If you want to rebase/retry this PR, check this box\n\nThis PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  true,
			reason: "",
		},
		{
			name:  "renovate PR edited without checkbox checked",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "edited",
				PullRequest: &ForgejoPullRequest{
					Body: "Update dependency\n - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box\n\nThis PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "no checked checkbox",
		},
		{
			name:  "renovate PR with empty body",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "edited",
				PullRequest: &ForgejoPullRequest{
					Body: "",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "no pull request body",
		},
		{
			name:  "renovate PR closed",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "closed",
				PullRequest: &ForgejoPullRequest{
					Body: "Update dependency\n\nThis PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  true,
			reason: "",
		},
		{
			name:  "renovate PR reopened",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "reopened",
				PullRequest: &ForgejoPullRequest{
					Body: "Update dependency\n\nThis PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  true,
			reason: "",
		},
		{
			name:  "non-renovate PR is ignored",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "edited",
				PullRequest: &ForgejoPullRequest{
					Body: "Some regular PR body with - [x] a checkbox",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "not a Renovate pull request",
		},
		{
			name:  "renovate PR opened is ignored",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "opened",
				PullRequest: &ForgejoPullRequest{
					Body: "This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "pull request action is not edited, closed, or reopened",
		},
		{
			name:  "pull request with nil payload",
			event: "pull_request",
			payload: ForgejoEvent{
				Action:     "edited",
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "no pull request in payload",
		},

		// Unsupported events
		{
			name:  "push event is not supported",
			event: "push",
			payload: ForgejoEvent{
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "unsupported event type: push",
		},
		{
			name:  "issue_comment event is not supported",
			event: "issue_comment",
			payload: ForgejoEvent{
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "unsupported event type: issue_comment",
		},
		{
			name:  "release event is not supported",
			event: "release",
			payload: ForgejoEvent{
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			valid:  false,
			reason: "unsupported event type: release",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			valid, reason := isValidForgejoEvent(tt.event, &tt.payload)
			if valid != tt.valid || reason != tt.reason {
				t.Errorf("expected valid=%v, reason=%q; got valid=%v, reason=%q", tt.valid, tt.reason, valid, reason)
			}
		})
	}
}
