package webhook

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	api "renovate-operator/api/v1alpha1"
	crdmanager "renovate-operator/internal/crdManager"
	"testing"

	"github.com/go-logr/logr"
)

func TestForgejoWebhook_Integration(t *testing.T) {
	tests := []struct {
		name             string
		event            string
		payload          ForgejoEvent
		namespace        string
		job              string
		expectedStatus   int
		expectedMessage  string
		shouldCallUpdate bool
	}{
		// Issue events
		{
			name:  "issue edited with renovate checkbox triggers schedule",
			event: "issues",
			payload: ForgejoEvent{
				Action: "edited",
				Issue: &ForgejoIssue{
					ID:    42,
					Title: "Dependency Dashboard",
					Body:  "This issue lists Renovate updates and detected dependencies.\n - [x] <!-- manual job -->Check this box to trigger a request for Renovate to run again on this repository",
				},
				Repository: ForgejoRepository{
					ID:       100,
					Name:     "repo",
					FullName: "example/repo",
				},
			},
			namespace:        "renovate-operator",
			job:              "my-job",
			expectedStatus:   http.StatusAccepted,
			expectedMessage:  "renovate job scheduled",
			shouldCallUpdate: true,
		},
		{
			name:  "issue edited without checkbox is ignored",
			event: "issues",
			payload: ForgejoEvent{
				Action: "edited",
				Issue: &ForgejoIssue{
					Title: "Dependency Dashboard",
					Body:  "This issue lists Renovate updates and detected dependencies.\n - [ ] <!-- manual job -->Check this box to trigger a request for Renovate to run again on this repository",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			namespace:        "renovate-operator",
			job:              "my-job",
			expectedStatus:   http.StatusOK,
			expectedMessage:  "event ignored",
			shouldCallUpdate: false,
		},
		{
			name:  "issue opened is ignored",
			event: "issues",
			payload: ForgejoEvent{
				Action: "opened",
				Issue: &ForgejoIssue{
					Body: "Some body",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			namespace:        "renovate-operator",
			job:              "my-job",
			expectedStatus:   http.StatusOK,
			expectedMessage:  "event ignored",
			shouldCallUpdate: false,
		},

		// Pull request events
		{
			name:  "renovate PR edited with checkbox triggers schedule",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "edited",
				PullRequest: &ForgejoPullRequest{
					ID:   123,
					Body: "Update dependency\n - [x] <!-- rebase-check -->If you want to rebase/retry this PR, check this box\n\nThis PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
				},
				Repository: ForgejoRepository{
					ID:       100,
					Name:     "repo",
					FullName: "example/repo",
				},
			},
			namespace:        "renovate-operator",
			job:              "my-job",
			expectedStatus:   http.StatusAccepted,
			expectedMessage:  "renovate job scheduled",
			shouldCallUpdate: true,
		},
		{
			name:  "renovate PR closed triggers schedule",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "closed",
				PullRequest: &ForgejoPullRequest{
					Body: "Update dependency\n\nThis PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			namespace:        "renovate-operator",
			job:              "my-job",
			expectedStatus:   http.StatusAccepted,
			expectedMessage:  "renovate job scheduled",
			shouldCallUpdate: true,
		},
		{
			name:  "non-renovate PR is ignored",
			event: "pull_request",
			payload: ForgejoEvent{
				Action: "edited",
				PullRequest: &ForgejoPullRequest{
					Body: "Some regular PR body",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			namespace:        "renovate-operator",
			job:              "my-job",
			expectedStatus:   http.StatusOK,
			expectedMessage:  "event ignored",
			shouldCallUpdate: false,
		},

		// Unsupported events
		{
			name:  "push event is ignored",
			event: "push",
			payload: ForgejoEvent{
				Repository: ForgejoRepository{FullName: "example/repo"},
			},
			namespace:        "renovate-operator",
			job:              "my-job",
			expectedStatus:   http.StatusOK,
			expectedMessage:  "event ignored",
			shouldCallUpdate: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			updateCalled := false
			mockManager := &mockWebhookManager{
				updateProjectStatusFunc: func(ctx context.Context, project string, jobId crdmanager.RenovateJobIdentifier, status api.RenovateProjectStatus) error {
					updateCalled = true
					if project != tt.payload.Repository.FullName {
						t.Errorf("expected project %s, got %s", tt.payload.Repository.FullName, project)
					}
					if jobId.Name != tt.job {
						t.Errorf("expected job name %s, got %s", tt.job, jobId.Name)
					}
					if jobId.Namespace != tt.namespace {
						t.Errorf("expected namespace %s, got %s", tt.namespace, jobId.Namespace)
					}
					if status != api.JobStatusScheduled {
						t.Errorf("expected status %s, got %s", api.JobStatusScheduled, status)
					}
					return nil
				},
			}

			server := &Server{
				manager: mockManager,
				logger:  logr.Discard(),
			}

			body, err := json.Marshal(tt.payload)
			if err != nil {
				t.Fatalf("failed to marshal payload: %v", err)
			}

			url := "/webhook/v1/forgejo"
			if tt.namespace != "" || tt.job != "" {
				url += "?"
				if tt.namespace != "" {
					url += "namespace=" + tt.namespace
				}
				if tt.job != "" {
					if tt.namespace != "" {
						url += "&"
					}
					url += "job=" + tt.job
				}
			}
			req := httptest.NewRequest(http.MethodPost, url, bytes.NewReader(body))
			req.Header.Set("Content-Type", "application/json")
			req.Header.Set("X-Forgejo-Event", tt.event)

			w := httptest.NewRecorder()
			server.forgejoWebhook(w, req)

			if w.Code != tt.expectedStatus {
				t.Errorf("expected status %d, got %d", tt.expectedStatus, w.Code)
			}

			var response map[string]string
			if err := json.Unmarshal(w.Body.Bytes(), &response); err != nil {
				t.Fatalf("failed to unmarshal response: %v", err)
			}

			if message, ok := response["message"]; ok {
				if message != tt.expectedMessage {
					t.Errorf("expected message %q, got %q", tt.expectedMessage, message)
				}
			}

			if updateCalled != tt.shouldCallUpdate {
				t.Errorf("expected updateCalled=%v, got %v", tt.shouldCallUpdate, updateCalled)
			}
		})
	}
}

func TestForgejoWebhook_MissingEventHeader(t *testing.T) {
	server := &Server{
		manager: &mockWebhookManager{},
		logger:  logr.Discard(),
	}

	payload := ForgejoEvent{
		Repository: ForgejoRepository{FullName: "example/repo"},
	}
	body, _ := json.Marshal(payload)

	req := httptest.NewRequest(http.MethodPost, "/webhook/v1/forgejo?namespace=default&job=test", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")

	w := httptest.NewRecorder()
	server.forgejoWebhook(w, req)

	if w.Code != http.StatusBadRequest {
		t.Errorf("expected status %d, got %d", http.StatusBadRequest, w.Code)
	}

	var response map[string]string
	json.Unmarshal(w.Body.Bytes(), &response)
	if response["error"] != "missing X-Forgejo-Event header" {
		t.Errorf("expected error about missing header, got %q", response["error"])
	}
}

func TestForgejoWebhook_MissingQueryParams(t *testing.T) {
	tests := []struct {
		name           string
		namespace      string
		job            string
		expectedStatus int
		expectedError  string
	}{
		{
			name:           "missing namespace",
			namespace:      "",
			job:            "test-job",
			expectedStatus: http.StatusBadRequest,
			expectedError:  "missing namespace or job query parameter",
		},
		{
			name:           "missing job",
			namespace:      "default",
			job:            "",
			expectedStatus: http.StatusBadRequest,
			expectedError:  "missing namespace or job query parameter",
		},
		{
			name:           "missing both parameters",
			namespace:      "",
			job:            "",
			expectedStatus: http.StatusBadRequest,
			expectedError:  "missing namespace or job query parameter",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			server := &Server{
				manager: &mockWebhookManager{},
				logger:  logr.Discard(),
			}

			// Use an issues event with valid checkbox so we get past validation
			payload := ForgejoEvent{
				Action: "edited",
				Issue: &ForgejoIssue{
					Body: "This issue lists Renovate updates and detected dependencies.\n - [x] <!-- manual job -->Check this box to trigger a request for Renovate to run again on this repository",
				},
				Repository: ForgejoRepository{FullName: "example/repo"},
			}
			body, _ := json.Marshal(payload)

			url := "/webhook/v1/forgejo"
			if tt.namespace != "" || tt.job != "" {
				url += "?"
				if tt.namespace != "" {
					url += "namespace=" + tt.namespace
				}
				if tt.job != "" {
					if tt.namespace != "" {
						url += "&"
					}
					url += "job=" + tt.job
				}
			}

			req := httptest.NewRequest(http.MethodPost, url, bytes.NewReader(body))
			req.Header.Set("Content-Type", "application/json")
			req.Header.Set("X-Forgejo-Event", "issues")

			w := httptest.NewRecorder()
			server.forgejoWebhook(w, req)

			if w.Code != tt.expectedStatus {
				t.Errorf("expected status %d, got %d", tt.expectedStatus, w.Code)
			}

			var response map[string]string
			json.Unmarshal(w.Body.Bytes(), &response)
			if response["error"] != tt.expectedError {
				t.Errorf("expected error %q, got %q", tt.expectedError, response["error"])
			}
		})
	}
}

func TestForgejoWebhook_InvalidJSON(t *testing.T) {
	server := &Server{
		manager: &mockWebhookManager{},
		logger:  logr.Discard(),
	}

	req := httptest.NewRequest(http.MethodPost, "/webhook/v1/forgejo?namespace=default&job=test-job", bytes.NewReader([]byte("invalid json")))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Forgejo-Event", "issues")

	w := httptest.NewRecorder()
	server.forgejoWebhook(w, req)

	if w.Code != http.StatusBadRequest {
		t.Errorf("expected status %d, got %d", http.StatusBadRequest, w.Code)
	}

	var response map[string]string
	json.Unmarshal(w.Body.Bytes(), &response)
	if response["error"] != "failed to decode payload" {
		t.Errorf("expected error 'failed to decode payload', got %q", response["error"])
	}
}

func TestForgejoWebhook_RealWorldDependencyDashboard(t *testing.T) {
	payload := ForgejoEvent{
		Action: "edited",
		Issue: &ForgejoIssue{
			ID:     42,
			Number: 1,
			Title:  "Dependency Dashboard",
			Body:   "# Dependency Dashboard\n\nThis issue lists Renovate updates and detected dependencies.\n\n## Pending Approval\n\nThese branches will be created by Renovate only once you click their checkbox below.\n\n - [x] <!-- approvePr-branch=renovate/golang-1.x -->chore(deps): update dependency golang to v1.23\n\n## Open\n\nThese updates have all been created already.\n\n - [ ] <!-- rebase-all-open-prs -->**Click on this checkbox to rebase all open PRs at once**\n",
		},
		Repository: ForgejoRepository{
			ID:       500,
			Name:     "renovate-config",
			FullName: "example/renovate-config",
		},
	}

	updateCalled := false
	mockManager := &mockWebhookManager{
		updateProjectStatusFunc: func(ctx context.Context, project string, jobId crdmanager.RenovateJobIdentifier, status api.RenovateProjectStatus) error {
			updateCalled = true
			if project != "example/renovate-config" {
				t.Errorf("expected project example/renovate-config, got %s", project)
			}
			return nil
		},
	}

	server := &Server{
		manager: mockManager,
		logger:  logr.Discard(),
	}

	body, _ := json.Marshal(payload)

	req := httptest.NewRequest(http.MethodPost, "/webhook/v1/forgejo?namespace=renovate-operator&job=codefloe", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Forgejo-Event", "issues")

	w := httptest.NewRecorder()
	server.forgejoWebhook(w, req)

	if w.Code != http.StatusAccepted {
		t.Errorf("expected status %d, got %d", http.StatusAccepted, w.Code)
	}

	var response map[string]string
	json.Unmarshal(w.Body.Bytes(), &response)
	if response["message"] != "renovate job scheduled" {
		t.Errorf("expected message 'renovate job scheduled', got %q", response["message"])
	}

	if !updateCalled {
		t.Error("expected UpdateProjectStatus to be called")
	}
}
