package webhook

import (
	"encoding/json"
	"io"
	"net/http"
)

// Forgejo webhook types and handler.
//
// The existing GitHub and GitLab handlers only process "edited" actions with
// Renovate checkbox validation. Reusing the GitHub handler for Forgejo does not
// work because Forgejo fires "issues" webhooks for every kind of issue
// mutation (title, labels, assignees, etc.), not just body edits. The GitHub
// handler accepts all "edited" events as long as the body is non-empty, but
// for Forgejo this leads to false triggers on non-body edits or missed
// triggers when the payload doesn't match GitHub's structure.
//
// This handler uses the X-Forgejo-Event header to dispatch by event type and
// applies Forgejo-specific filtering:
//
//   - issues (edited): only if the issue body is a Renovate Dependency
//     Dashboard and contains a checked checkbox
//   - pull_request (edited/closed/reopened): only for PRs generated by
//     Renovate, identified by body content rather than author username
//
// Additionally, Forgejo uses X-Forgejo-Signature for HMAC authentication
// instead of X-Hub-Signature-256.

type ForgejoEvent struct {
	Action      string              `json:"action"`
	PullRequest *ForgejoPullRequest `json:"pull_request,omitempty"`
	Issue       *ForgejoIssue       `json:"issue,omitempty"`
	Repository  ForgejoRepository   `json:"repository"`
}

type ForgejoPullRequest struct {
	ID     int          `json:"id"`
	Number int          `json:"number"`
	Body   string       `json:"body"`
	User   *ForgejoUser `json:"user,omitempty"`
}

type ForgejoIssue struct {
	ID     int    `json:"id"`
	Number int    `json:"number"`
	Title  string `json:"title"`
	Body   string `json:"body"`
}

type ForgejoRepository struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	FullName string `json:"full_name"`
}

type ForgejoUser struct {
	Login string `json:"login"`
}

func (s *Server) forgejoWebhook(w http.ResponseWriter, r *http.Request) {
	event := r.Header.Get("X-Forgejo-Event")
	if event == "" {
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "missing X-Forgejo-Event header"})
		return
	}

	body, err := io.ReadAll(r.Body)
	if err != nil {
		s.writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to read request body"})
		return
	}

	var raw ForgejoEvent
	if err := json.Unmarshal(body, &raw); err != nil {
		s.logger.Error(err, "failed to decode Forgejo webhook payload. Not processing.")
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "failed to decode payload"})
		return
	}

	payload, valid := parseForgejoPayload(event, &raw)
	if !valid {
		s.logger.V(5).Info("failed to parse webhook payload")
		s.writeJSON(w, http.StatusOK, map[string]string{"message": "event ignored"})
		return
	}

	s.handleWebhookTrigger(w, r, body, payload)
}

// parseForgejoPayload normalizes a raw Forgejo event into a WebhookPayload and
// validates it. The X-Forgejo-Event header value is used to determine the event
// type. Returns false when the event should be ignored.
func parseForgejoPayload(event string, raw *ForgejoEvent) (WebhookPayload, bool) {
	var eventType, current string
	switch event {
	case "issues":
		eventType = "issue"
		if raw.Issue != nil {
			current = raw.Issue.Body
		}
	case "pull_request":
		eventType = "pull_request"
		if raw.PullRequest == nil {
			return WebhookPayload{}, false
		}
		current = raw.PullRequest.Body
	default:
		return WebhookPayload{}, false
	}

	return WebhookPayload{
		Provider:  "Forgejo",
		Project:   raw.Repository.FullName,
		Event:     event,
		Action:    raw.Action,
		EventType: eventType,
		Body:      WebhookBody{Current: current},
	}, true
}
