package webhook

import (
	"encoding/json"
	"net/http"
	api "renovate-operator/api/v1alpha1"
	crdmanager "renovate-operator/internal/crdManager"
	"renovate-operator/internal/types"
)

// Forgejo webhook types and handler.
//
// The existing GitHub and GitLab handlers only process "edited" actions with
// Renovate checkbox validation. Reusing the GitHub handler for Forgejo does not
// work because Forgejo fires "issues" webhooks for every kind of issue
// mutation (title, labels, assignees, etc.), not just body edits. The GitHub
// handler accepts all "edited" events as long as the body is non-empty, but
// for Forgejo this leads to false triggers on non-body edits or missed
// triggers when the payload doesn't match GitHub's structure.
//
// This handler uses the X-Forgejo-Event header to dispatch by event type and
// applies Forgejo-specific filtering:
//
//   - issues (edited): only if the issue body is a Renovate Dependency
//     Dashboard and contains a checked checkbox
//   - pull_request (edited/closed/reopened): only for PRs generated by
//     Renovate, identified by body content rather than author username
//
// Additionally, Forgejo uses X-Forgejo-Signature for HMAC authentication
// instead of X-Hub-Signature-256.

type ForgejoEvent struct {
	Action      string              `json:"action"`
	PullRequest *ForgejoPullRequest `json:"pull_request,omitempty"`
	Issue       *ForgejoIssue       `json:"issue,omitempty"`
	Repository  ForgejoRepository   `json:"repository"`
}

type ForgejoPullRequest struct {
	ID     int          `json:"id"`
	Number int          `json:"number"`
	Body   string       `json:"body"`
	User   *ForgejoUser `json:"user,omitempty"`
}

type ForgejoIssue struct {
	ID     int    `json:"id"`
	Number int    `json:"number"`
	Title  string `json:"title"`
	Body   string `json:"body"`
}

type ForgejoRepository struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	FullName string `json:"full_name"`
}

type ForgejoUser struct {
	Login string `json:"login"`
}

func (s *Server) forgejoWebhook(w http.ResponseWriter, r *http.Request) {
	event := r.Header.Get("X-Forgejo-Event")
	if event == "" {
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "missing X-Forgejo-Event header"})
		return
	}

	var payload ForgejoEvent
	err := json.NewDecoder(r.Body).Decode(&payload)
	if err != nil {
		s.logger.Error(err, "failed to decode Forgejo webhook payload. Not processing.")
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "failed to decode payload"})
		return
	}

	valid, reason := isValidForgejoEvent(event, &payload)
	if !valid {
		s.logger.Info("ignoring Forgejo webhook event", "event", event, "repository", payload.Repository.FullName, "reason", reason)
		s.writeJSON(w, http.StatusOK, map[string]string{"message": "event ignored", "reason": reason})
		return
	}

	namespace := r.URL.Query().Get("namespace")
	job := r.URL.Query().Get("job")
	if namespace == "" || job == "" {
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "missing namespace or job query parameter"})
		return
	}

	s.logger.Info("received Forgejo event", "event", event, "repository", payload.Repository.FullName, "action", payload.Action)
	err = s.manager.UpdateProjectStatus(
		r.Context(),
		payload.Repository.FullName,
		crdmanager.RenovateJobIdentifier{
			Name:      job,
			Namespace: namespace,
		},
		&types.RenovateStatusUpdate{
			Status:   api.JobStatusScheduled,
			Priority: 1,
		},
	)
	if err != nil {
		s.logger.Error(err, "Failed to process Forgejo webhook for repo", "repo", payload.Repository.FullName)
		s.writeJSON(w, http.StatusInternalServerError, map[string]string{"message": "failed to process webhook"})
		return
	}

	s.writeJSON(w, http.StatusAccepted, map[string]string{"message": "renovate job scheduled", "repository": payload.Repository.FullName})
}

func isValidForgejoEvent(event string, payload *ForgejoEvent) (bool, string) {
	switch event {
	case "issues":
		if payload.Action != "edited" {
			return false, "issue action is not edited"
		}
		if payload.Issue == nil || payload.Issue.Body == "" {
			return false, "no issue body"
		}
		if !verifyRenovateDescriptionChange(payload.Issue.Body) {
			return false, "not a valid renovate checkbox change"
		}
		return true, ""

	case "pull_request":
		if payload.PullRequest == nil {
			return false, "no pull request in payload"
		}
		if payload.PullRequest.Body == "" {
			return false, "no pull request body"
		}
		if !isRenovateContent(payload.PullRequest.Body) {
			return false, "not a Renovate pull request"
		}
		switch payload.Action {
		case "closed", "reopened":
			return true, ""
		case "edited":
			if !hasCheckboxBeenChecked(payload.PullRequest.Body) {
				return false, "no checked checkbox"
			}
			return true, ""
		default:
			return false, "pull request action is not edited, closed, or reopened"
		}

	default:
		return false, "unsupported event type: " + event
	}
}
