package webhook

import (
	"encoding/json"
	"io"
	"net/http"
)

// Gitea webhook types and handler.
//
// Gitea currently uses the same payload format and event semantics as Forgejo,
// but the endpoint, types, and processing are deliberately independent from
// forgejo.go: the projects have diverged before (X-Gitea-Event vs
// X-Forgejo-Event headers) and may diverge further.
//
// This handler uses the X-Gitea-Event header to dispatch by event type and
// applies the following filtering:
//
//   - issues (edited): only if the issue body is a Renovate Dependency
//     Dashboard and contains a checked checkbox
//   - pull_request (edited/closed/reopened): only for PRs generated by
//     Renovate, identified by body content rather than author username
//
// Additionally, Gitea uses X-Gitea-Signature for HMAC authentication instead
// of X-Hub-Signature-256.

type GiteaEvent struct {
	Action      string            `json:"action"`
	PullRequest *GiteaPullRequest `json:"pull_request,omitempty"`
	Issue       *GiteaIssue       `json:"issue,omitempty"`
	Repository  GiteaRepository   `json:"repository"`
}

type GiteaPullRequest struct {
	ID     int        `json:"id"`
	Number int        `json:"number"`
	Body   string     `json:"body"`
	User   *GiteaUser `json:"user,omitempty"`
}

type GiteaIssue struct {
	ID     int    `json:"id"`
	Number int    `json:"number"`
	Title  string `json:"title"`
	Body   string `json:"body"`
}

type GiteaRepository struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	FullName string `json:"full_name"`
}

type GiteaUser struct {
	Login string `json:"login"`
}

func (s *Server) giteaWebhook(w http.ResponseWriter, r *http.Request) {
	event := r.Header.Get("X-Gitea-Event")
	if event == "" {
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "missing X-Gitea-Event header"})
		return
	}

	body, err := io.ReadAll(r.Body)
	if err != nil {
		s.writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to read request body"})
		return
	}

	var raw GiteaEvent
	if err := json.Unmarshal(body, &raw); err != nil {
		s.logger.Error(err, "failed to decode Gitea webhook payload. Not processing.")
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "failed to decode payload"})
		return
	}

	payload, valid := parseGiteaPayload(event, &raw)
	if !valid {
		s.logger.V(5).Info("failed to parse webhook payload")
		s.writeJSON(w, http.StatusOK, map[string]string{"message": "event ignored"})
		return
	}

	s.handleWebhookTrigger(w, r, body, payload)
}

// parseGiteaPayload normalizes a raw Gitea event into a WebhookPayload and
// validates it. The X-Gitea-Event header value is used to determine the event
// type. Returns false when the event should be ignored.
func parseGiteaPayload(event string, raw *GiteaEvent) (WebhookPayload, bool) {
	var eventType, current string
	switch event {
	case "issues":
		eventType = "issue"
		if raw.Issue != nil {
			current = raw.Issue.Body
		}
	case "pull_request":
		eventType = "pull_request"
		if raw.PullRequest == nil {
			return WebhookPayload{}, false
		}
		current = raw.PullRequest.Body
	default:
		return WebhookPayload{}, false
	}

	return WebhookPayload{
		Provider:  "Gitea",
		Project:   raw.Repository.FullName,
		Event:     event,
		Action:    raw.Action,
		EventType: eventType,
		Body:      WebhookBody{Current: current},
	}, true
}
