package webhook

import (
	"encoding/json"
	"io"
	"net/http"

	api "renovate-operator/api/v1alpha1"
	"renovate-operator/internal/types"
	"renovate-operator/metricStore"
)

// Gitea webhook types and handler.
//
// Gitea currently uses the same payload format and event semantics as Forgejo,
// but the endpoint, types, and processing are deliberately independent from
// forgejo.go: the projects have diverged before (X-Gitea-Event vs
// X-Forgejo-Event headers) and may diverge further.
//
// This handler uses the X-Gitea-Event header to dispatch by event type and
// applies the following filtering:
//
//   - issues (edited): only if the issue body is a Renovate Dependency
//     Dashboard and contains a checked checkbox
//   - pull_request (edited/closed/reopened): only for PRs generated by
//     Renovate, identified by body content rather than author username
//
// Additionally, Gitea uses X-Gitea-Signature for HMAC authentication instead
// of X-Hub-Signature-256.

type GiteaEvent struct {
	Action      string            `json:"action"`
	PullRequest *GiteaPullRequest `json:"pull_request,omitempty"`
	Issue       *GiteaIssue       `json:"issue,omitempty"`
	Repository  GiteaRepository   `json:"repository"`
}

type GiteaPullRequest struct {
	ID     int        `json:"id"`
	Merged bool       `json:"merged"`
	Number int        `json:"number"`
	Body   string     `json:"body"`
	User   *GiteaUser `json:"user,omitempty"`
}

type GiteaIssue struct {
	ID     int    `json:"id"`
	Number int    `json:"number"`
	Title  string `json:"title"`
	Body   string `json:"body"`
}

type GiteaRepository struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	FullName string `json:"full_name"`
}

type GiteaUser struct {
	Login string `json:"login"`
}

func (s *Server) giteaWebhook(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	const provider = "gitea"

	event := r.Header.Get("X-Gitea-Event")
	if event == "" {
		metricStore.IncWebhookRequest(ctx, provider, "rejected")
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "missing X-Gitea-Event header"})
		return
	}

	body, err := io.ReadAll(r.Body)
	if err != nil {
		metricStore.IncWebhookRequest(ctx, provider, "rejected")
		s.writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to read request body"})
		return
	}

	var payload GiteaEvent
	if err := json.Unmarshal(body, &payload); err != nil {
		metricStore.IncWebhookPayloadDecodeFailure(ctx, provider)
		metricStore.IncWebhookRequest(ctx, provider, "rejected")
		s.logger.Error(err, "failed to decode Gitea webhook payload. Not processing.")
		s.writeJSON(w, http.StatusBadRequest, map[string]string{"error": "failed to decode payload"})
		return
	}

	valid, reason := isValidGiteaEvent(event, &payload)
	if !valid {
		metricStore.IncWebhookRequest(ctx, provider, "ignored")
		s.logger.Info("ignoring Gitea webhook event", "event", event, "repository", payload.Repository.FullName, "reason", reason)
		s.writeJSON(w, http.StatusOK, map[string]string{"message": "event ignored", "reason": reason})
		return
	}

	namespace := r.URL.Query().Get("namespace")
	jobName := r.URL.Query().Get("job")
	project := payload.Repository.FullName

	checker := buildAuthCheckerFromRequest(r, body, s.manager)
	jobId, err := FindAndAuthenticateJob(ctx, s.manager, namespace, jobName, project, checker)
	if err != nil {
		s.recordResolverAuthFailure(ctx, provider, err, signatureWasUsed(r))
		metricStore.IncWebhookRequest(ctx, provider, "rejected")
		s.logger.Info("webhook resolve failed", "event", event, "project", project, "error", err)
		s.handleResolverError(w, err)
		return
	}

	s.logger.Info("received Gitea event", "event", event, "repository", project, "action", payload.Action)
	err = s.manager.UpdateProjectStatus(
		ctx,
		project,
		jobId,
		&types.RenovateStatusUpdate{
			Status:   api.JobStatusScheduled,
			Priority: 1,
		},
	)
	if s.handleUpdateProjectStatusError(w, err, project, jobId.Name, jobId.Namespace) {
		metricStore.IncWebhookRequest(ctx, provider, "rejected")
		return
	}

	metricStore.IncWebhookRequest(ctx, provider, "accepted")
	s.writeJSON(w, http.StatusAccepted, map[string]string{"message": "renovate job scheduled", "repository": project})
}

func isValidGiteaEvent(event string, payload *GiteaEvent) (bool, string) {
	switch event {
	case "issues":
		if payload.Action != "edited" {
			return false, "issue action is not edited"
		}
		if payload.Issue == nil || payload.Issue.Body == "" {
			return false, "no issue body"
		}
		if !verifyRenovateDescriptionChange(payload.Issue.Body) {
			return false, "not a valid renovate checkbox change"
		}
		return true, ""

	case "pull_request":
		if payload.PullRequest == nil {
			return false, "no pull request in payload"
		}
		if payload.PullRequest.Merged {
			return true, ""
		}
		if payload.PullRequest.Body == "" {
			return false, "no pull request body"
		}
		if !isRenovateContent(payload.PullRequest.Body) {
			return false, "not a Renovate pull request"
		}
		switch payload.Action {
		case "closed", "reopened":
			return true, ""
		case "edited":
			if !hasCheckboxBeenChecked(payload.PullRequest.Body) {
				return false, "no checked checkbox"
			}
			return true, ""
		default:
			return false, "pull request action is not edited, closed, or reopened"
		}

	default:
		return false, "unsupported event type: " + event
	}
}
