
name: Build main Image

on:
  push:
    branches:
      - main

jobs:
  build-operator:
    uses: mogenius/github-actions/.github/workflows/build-multiarch.yml@2af15d14616af5992e6106b6a59b42e95136ea7c # v1.7.6
    secrets: inherit
    with:
      version: "main"
      image: ghcr.io/mogenius/renovate-operator
      push_latest: false
