
name: Build main Image

on:
  push:
    branches:
      - main

jobs:
  build-operator:
    uses: mogenius/github-actions/.github/workflows/build-multiarch.yml@2dd56b0d0223d0c7fd80d9f978186d02cb0546dd # v1.2.0
    secrets: inherit
    with:
      version: "main"
      image: ghcr.io/mogenius/renovate-operator
      push_latest: false
