
name: Build main Image

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-operator:
    uses: mogenius/github-actions/.github/workflows/build-multiarch.yml@157683e012c4ba4e22e86fe4e00ddf295215c483 # v1.9.2
    secrets: inherit
    with:
      version: "main"
      image: ghcr.io/mogenius/renovate-operator
      push_latest: false
