name: Helm

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: mogenius/github-actions/.github/workflows/helm-lint.yml@003b4f8d0dc6b7c9f5b5e8f94b722516b6fdd7a8 # v1.7.7
    with:
      path: ./charts/renovate-operator

  tests:
    uses: mogenius/github-actions/.github/workflows/helm-unittest.yml@003b4f8d0dc6b7c9f5b5e8f94b722516b6fdd7a8 # v1.7.7
    with:
      path: ./charts/renovate-operator


  template:
    uses: mogenius/github-actions/.github/workflows/helm-template.yml@003b4f8d0dc6b7c9f5b5e8f94b722516b6fdd7a8 # v1.7.7
    with:
      path: ./charts/renovate-operator
      namespace: renovate-operator
      update_dependencies: true
      values: |
        metrics:
          dashboard:
            enabled: true
