name: Helm

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: mogenius/github-actions/.github/workflows/helm-lint.yml@7af6889cb36e5da3ced9baef9d887709fd034e48 # v1.6.0
    with:
      path: ./charts/renovate-operator

  tests:
    uses: mogenius/github-actions/.github/workflows/helm-unittest.yml@7af6889cb36e5da3ced9baef9d887709fd034e48 # v1.6.0
    with:
      path: ./charts/renovate-operator


  template:
    uses: mogenius/github-actions/.github/workflows/helm-template.yml@7af6889cb36e5da3ced9baef9d887709fd034e48 # v1.6.0
    with:
      path: ./charts/renovate-operator
      namespace: renovate-operator
      update_dependencies: true
      values: |
        metrics:
          dashboard:
            enabled: true
