name: Helm

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: mogenius/github-actions/.github/workflows/helm-lint.yml@ae3aeb8b5d36732180ac9e7bf55938f1510fc1db # v1.1.0
    with:
      path: ./charts/renovate-operator

  tests:
    uses: mogenius/github-actions/.github/workflows/helm-unittest.yml@ae3aeb8b5d36732180ac9e7bf55938f1510fc1db # v1.1.0
    with:
      path: ./charts/renovate-operator


  template:
    uses: mogenius/github-actions/.github/workflows/helm-template.yml@ae3aeb8b5d36732180ac9e7bf55938f1510fc1db # v1.1.0
    with:
      path: ./charts/renovate-operator
      namespace: renovate-operator
      update_dependencies: true
      values: |
        metrics:
          dashboard:
            enabled: true
